# 5.16 List 2 Dimensi

Berfungsi untuk menempatkan sebuah list di dalam list. Penggambaran seperti sebuah matrix.

In [1]:
#masukkan data matrix
#penggunaan list 2 dimensi menggunakan kurung siku
matrix = [
    [1,2,3,4],
    [2,3,0,1],
    [0,5,0,4],
    [3,1,9,5]
]

print(matrix) #akan tercetak list di dalam variabel matrix

[[1, 2, 3, 4], [2, 3, 0, 1], [0, 5, 0, 4], [3, 1, 9, 5]]


In [2]:
#penghitungan list dimulai dari baris 0 sampai baris-n
#penghitungan list juga dimulai dari kolom 0 sampai kolom-n

#memanggil matrix pada baris index nomor 1
print(f"Hasil matrix baris index nomor 1 adalah : {matrix [1]}")


#memanggil matrix pada baris index nomor 1 dan kolom index nomor 2
print(f"Hasil matrix baris index nomor 1 dan kolom index nomor 2 adalah : {matrix[1][2]}")

Hasil matrix baris index nomor 1 adalah : [2, 3, 0, 1]
Hasil matrix baris index nomor 1 dan kolom index nomor 2 adalah : 0


In [3]:
#berfungsi untuk mengubah nilai index dalam baris dan kolom matrix menjadi nilai index yang baru

#pada code ini akan dicoba merubah matrix baris index nomor 2 dan kolom index nomor 3 menjadi 8
matrix[2][3]=8
print(f"Nilai baru pada matrix baris index nomor dan kolom index nomor 3 adalah : {matrix[2][3]}")


#data yang diubah akan menjadi data permanen
#sehingga ketika mencetak ulang matrix, maka matrix yang didapat adalah matrix dengan data terbaru
print(f"Data terbaru dalam matrix : {matrix}")

Nilai baru pada matrix baris index nomor dan kolom index nomor 3 adalah : 8
Data terbaru dalam matrix : [[1, 2, 3, 4], [2, 3, 0, 1], [0, 5, 0, 8], [3, 1, 9, 5]]


In [4]:
#cara memanggil anggota dari list 2 dimensi

#akan digunakan fungsi for untuk memanggil anggota dari list 2 dimensi
for baris in matrix: #selesain dulu disini
    print(baris)
    #apabila print baris sudah selesai maka selanjutnya akan mencetak kolom
    
    for kolom in baris: #baru selesain disini
        print(kolom)
        
        #sehingga hasil print yang didapatkan adalah pengulangan anggota-anggota di dalam matrix baris
        #dilakukan pengulangan sampai setiap baris dari data list sudah terbaca semua

[1, 2, 3, 4]
1
2
3
4
[2, 3, 0, 1]
2
3
0
1
[0, 5, 0, 8]
0
5
0
8
[3, 1, 9, 5]
3
1
9
5


# 5.17 Tuples

List namun tidak dapat mengubah isi data.

In [5]:
#perbedaan tuples dan list diketahui dengan penggunaan tutup kurung
#list menggunakan kurung siku, sedangkan tuples menggunakan kurung biasa

#dimasukkan isi dalam data bilangan
bilangan = (2,3,0,1,0,5,0,4,0,4)

#seperti list, akan mencetak index nomor 0, dimana index nomor 0 merupakan urutan paling awal dalam list
print(f"Data urutan ke-0 dalam bilangan adalah : {bilangan[0]}")

Data urutan ke-0 dalam bilangan adalah : 2


In [6]:
#memanggil index nomor 3 sampai index nomor 5 (sesuai syntax pada python)
print(bilangan[3:6])

(1, 0, 5)


In [7]:
#penggunaan for untuk mencetak isi yang dicari dengan pengulangan satu persatu
#sehingga list yang keluar akan berupa baris kebawah
for isi in angka[3:5]:
    print(isi)

NameError: name 'angka' is not defined

In [8]:
#penggunaan remove untuk menghapus isi list dalam data
bilangan.remove(3)

#akan terjadi error karena penggunaan tuples tidak dapat mengubah isi dalam data
#sehingga tidak dapat menghapus isi dalam data

AttributeError: 'tuple' object has no attribute 'remove'

In [9]:
#penggunaan append untuk menambahkan isi dalam data
bilangan.append(10)

#akan terjadi error karena penggunaan tuples tidak dapat mengubah isi data
#sehingga tidak dapat menambah isi dalam data

AttributeError: 'tuple' object has no attribute 'append'

In [10]:
#penggunaan count adalah untuk menghitung banyaknya isi dalam data yang ingin dicari
#dalam code ini akan dicari berapa banyak angka 0 dalam data bilangan
print(f"Banyaknya angka 0 dalam data bilangan adalah : {bilangan.count(0)}")

#penggunaan index berfungsi untuk mencari isi dalam data sesuai urutan yang akan dipanggil
#dalam code ini akan memanggil isi dengan index nomor 3 dalam data
print(f"Isi di index nomor 3 dalam data bilangan adalah : {bilangan.index(3)}")

Banyaknya angka 0 dalam data bilangan adalah : 4
Isi di index nomor 3 dalam data bilangan adalah : 1


# 5.18 Dictionaries

Digunakan jika data nya terkait satu sama lain. 

In [11]:
#untuk memasukkan data dalam dictionary dapat menggunakan kurung kurawal
#sehingga dimasukkan data seseorang sebagai berikut : 
data1 = {
    "Nama" : "Jeon Jungkook",
    "Umur" : 26,                 #selalu menggunakan koma setelah objek data dimasukkan
    "Tempat Tinggal" : "Korea Selatan",
    "Pekerjaan" : "Penyanyi"     #untuk objek data paling terakhir tidak diperlukan koma
}

In [12]:
#data akan tercetak apabila kata kunci yang dipakai sesuai dengan yang ada di dalam data
#misal seperti persamaan pada penggunaan huruf kapital, huruf kecil, simbol, dll

print(data1['Nama'])

Jeon Jungkook


In [13]:
#data akan menghasilkan error apabila kata kunci yang dipakai tidak sesuai dengan yang ada di dalam data
print(data1['nama'])

KeyError: 'nama'

In [14]:
#tidak seperti kode di atas yang menghasilkan error, terdapat fungsi 'get' untuk pemanggilan yang salah namun tidak error
#sehingga fungsi 'get' digunakan agar mencegah sistem untuk menampilakn error

#pada code ini akan diberikan pemanggilan sesuai kata kunci dalam dict
print("Hasil pemanggilan get sesuai kata kunci yang ada dalam data :")
print(f"Umur Jeon Jungkook -> {data1.get('Umur')}")


#pada code ini akan diberikan pemanggilan tidak sesuai kata kunci dalam dict
#kata kunci dapat disebut salah karena dalam dict Umur menggunakan huruf kapital pada karakter U
print("\n")
print("Hasil dari pemanggilan get tidak sesuai kata kunci yang ada dalam data :")
print(f"umur Jeon Jungkook -> {data1.get('umur')}")
#output yang akan didapatkan adalah None


#selanjutnya fungsi 'get' dapat melihat apakah suatu objek data terdapat dalam data atau tidak
#pada contoh kode ini akan dicari Pendidikan terakhir, dimana Pendidikan terakhir tidak terdapat dalam data dict
print("\n")
print("Hasil dari pemanggilan get yang tidak ada kata kuncinya dalam data : ")
print(f"Pendidikan terakhir Jeon Jungkook -> {data1.get('Pendidikan Terakhir')}")

Hasil pemanggilan get sesuai kata kunci yang ada dalam data :
Umur Jeon Jungkook -> 26


Hasil dari pemanggilan get tidak sesuai kata kunci yang ada dalam data :
umur Jeon Jungkook -> None


Hasil dari pemanggilan get yang tidak ada kata kuncinya dalam data : 
Pendidikan terakhir Jeon Jungkook -> None


In [15]:
#untuk mencetak hasil Sekolah Asal, maka fungsi 'get' dapat digunakan sebagai berikut :

#pada kode ini akan tercetak Sekolah Asal Jeon Jungkook
print(f"Pendidikan terakhir Jeon Jungkook : {data1.get('Pendidikan terakhir','Sarjana Broadcasting and Entertainment')}")

#namun data yang akan dihasilkan tidak permanen, sehingga jika kita mencetak data terbaru, output yang didapat adalah data lama
print("\nData Jeon Jungkook : ")
print(data1)

Pendidikan terakhir Jeon Jungkook : Sarjana Broadcasting and Entertainment

Data Jeon Jungkook : 
{'Nama': 'Jeon Jungkook', 'Umur': 26, 'Tempat Tinggal': 'Korea Selatan', 'Pekerjaan': 'Penyanyi'}


In [16]:
#untuk menambahkan data dalam dict

data1['Pendidikan terakhir'] = 'Sarjana Broadcasting and Entertainment'
data1['Pacar'] = 'Adina'

#data yang dimasukkan akan permanen

In [17]:
#akan didapat data terbaru
print(data1)

{'Nama': 'Jeon Jungkook', 'Umur': 26, 'Tempat Tinggal': 'Korea Selatan', 'Pekerjaan': 'Penyanyi', 'Pendidikan terakhir': 'Sarjana Broadcasting and Entertainment', 'Pacar': 'Adina'}


In [18]:
for data in data1:
    print(data, ':', data1[data])

Nama : Jeon Jungkook
Umur : 26
Tempat Tinggal : Korea Selatan
Pekerjaan : Penyanyi
Pendidikan terakhir : Sarjana Broadcasting and Entertainment
Pacar : Adina


In [19]:
#program membaca sandi AN dalam pramuka

#masukkan data sandi AN
AN = {
    "n" : "A",
    "o" : "B",
    "p" : "C",
    "q" : "D",
    "r" : "E",
    "s" : "F",
    "t" : "G",
    "u" : "H",
    "v" : "I",
    "w" : "J",
    "x" : "K",
    "y" : "L",
    "z" : "M",
    "a" : "N",
    "b" : "O",
    "c" : "P",
    "d" : "Q",
    "e" : "R",
    "f" : "S",
    "g" : "T",
    "h" : "U",
    "i" : "V",
    "j" : "W",
    "k" : "X",
    "l" : "Y",
    "m" : "Z"
}

In [20]:
sandi_AN = input("Masukkan sandi yang ingin dicari : ")
huruf_AN = ""

for isi in sandi_AN :
    #akan melakukan pemanggilan dalam setiap sandi AN apabila isi yang dimasukkan terdapat dalam data AN
    huruf_AN += AN.get(isi) + " "
print(f"Hasil dari sandi adalah : {huruf_AN}")

Masukkan sandi yang ingin dicari : nqvan
Hasil dari sandi adalah : A D I N A 


# 5.19 Fungsi dalam Python

In [21]:
#mencetak format perkenalan

#def merupakan tanda kode program merupakan suatu fungsi
def biodata(nama_panjang, prodi, angkatan, jalur_masuk):
    print(f"Halo! Perkenalkan saya {nama_panjang} dari prodi {prodi} angkatan {angkatan} jalur masuk saya adalah {jalur_masuk}")
    #pada code ini menggunakan fungsi format string
    #tujuannya agar memudahkan penulisan nilai variabel pada parameter yang ingin dicetak pada print

In [22]:
#penggunaan fungsi input karena akan menghasilkan pencetakan parameter
#input harus diisi agar tidak terjadi error ataupun tidak berjalannya suatu code

nama_panjang = input("Nama Panjang : ")
prodi = input("Prodi : ")
angkatan = input("Angkatan :")
jalur_masuk = input("Jalur Masuk : ")

biodata(nama_panjang, prodi, angkatan, jalur_masuk)
#tidak menggunakan print karena pencetakan dan pendefinisian telah ditulis pada code sebelumnya

Nama Panjang : Adina Nur Halimah Sanwani
Prodi : Matematika
Angkatan :2022
Jalur Masuk : SNMPTN
Halo! Perkenalkan saya Adina Nur Halimah Sanwani dari prodi Matematika angkatan 2022 jalur masuk saya adalah SNMPTN


In [23]:
#fungsi untuk menghitung sebuah luas jenis bidang

def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    #return berfungsi untuk mengembalikan nilai dari sebuah fungsi
    return luas
def luas_persegi(sisi):
    luas = sisi**2
    return luas
def luas_persegi_panjang(panjang,lebar):
    luas = panjang*lebar
    return luas

In [24]:
jenis_bidang = input("Tulis jenis bidangnya : ")

#penggunaan if dan elif untuk penggabungan 2 atau lebih parameter yang akan dibuat
if jenis_bidang.upper() == "SEGITIGA" :
    alas = float(input('Berapakah panjang alasnya? '))
    tinggi = float(input('Berapakah tingginya? '))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
    
#pada if atau elif bila digabungkan dengan fungsi input, maka tambahkan upper sebagai kata kunci
elif jenis_bidang.upper() == 'PERSEGI':
    sisi = float(input('Berapakah panjang sisinya? '))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == 'PERSEGI PANJANG':
    panjang = float(input('Berapakah panjang sisinya? '))
    lebar = float(input('Berapakah lebar sisinya? '))
    luas = luas_persegi_panjang(panjang,lebar)
    print(f"Luas {jenis_bidang} adalah {luas}")
else : 
    print(f"Maaf bidang {jenis_bidang} yang anda masukkan tidak ada.")
    print("Pilihan cuma SEGITIGA, PERSEGI dan PERSEGI PANJANG.")
    print("Terimakasih")

Tulis jenis bidangnya : persegi panjang
Berapakah panjang sisinya? 7
Berapakah lebar sisinya? 8
Luas persegi panjang adalah 56.0


# 5.20 Numpy

In [25]:
#np = numpy = numeric python

import numpy as np #gunakan code ini agar numpy terbaca oleh python
#berfungsi untuk memanggil library numpy

#diberikan data array untuk membuat matrix dengan ordo 4x4
x = np.array([[0,1,9,7],[3,1,9,5],[2,3,1,4],[9,8,1,3]])
print(x)

[[0 1 9 7]
 [3 1 9 5]
 [2 3 1 4]
 [9 8 1 3]]


In [26]:
#diberikan data array untuk membuat matrix dengan ordo 1x4
y = np.array([1,3,5,7])

#seperti pada materi aljabar elementer dimana suatu matrix baris yang berordo 1xn juga merupakan vector baris
print(y)

[1 3 5 7]


In [27]:
#perhatikan perbedaan dalam penggunaan banyak nya kurung siku

#akan dimasukkan data seperti berikut
z = np.array([[[0,1,2,3],[0,8,1,3]],
               [[8,8,8,4],[9,5,6,2]],
               [[8,1,5,1],[3,1,5,7]]])

#penggunaan kurung siku seperti ini akan menghasilkan dimensi 3
#banyak kurung sikut sebanyak 3 akan menghasilkan dimensi 3
print(z)

[[[0 1 2 3]
  [0 8 1 3]]

 [[8 8 8 4]
  [9 5 6 2]]

 [[8 1 5 1]
  [3 1 5 7]]]


In [28]:
#bila kurung siku terdapat sebanyak 5 maka akan menghasilkan dimensi 5
zz = np.array([[[[[0,1,2,3],[0,8,1,3]]]],
               [[[[8,8,8,4],[9,5,6,2]]]],
               [[[[8,1,5,1],[3,1,5,7]]]]])
print(zz)

[[[[[0 1 2 3]
    [0 8 1 3]]]]



 [[[[8 8 8 4]
    [9 5 6 2]]]]



 [[[[8 1 5 1]
    [3 1 5 7]]]]]


In [29]:
#ndim berfungsi untuk mengetahui data yang dimasukkan termasuk dimensi berapa
print(f"Data x merupakan dimensi : {x.ndim}")
print(f"Data y merupakan dimensi : {y.ndim}")
print(f"Data z merupakan dimensi : {z.ndim}")
print(f"Data zz merupakan dimensi : {zz.ndim}")

#dimensi 1 untuk data berupa vektor
#dimensi 2 untuk data berupa matrix
#dimensi 3 untuk data lebih tinggi dari matrix, misal sebuah data memiliki baris, kolom, tinggi

Data x merupakan dimensi : 2
Data y merupakan dimensi : 1
Data z merupakan dimensi : 3
Data zz merupakan dimensi : 5


In [30]:
#shape berfungsi untuk mengembalikan tupel dengan setiap index memiliki jumlah elemen yang sesuai
#atau shape berfungsi untuk menghasilkan sebuah tuple yang berisikan panjang sebuah array pada tiap dimensi

print(f"Shape pada data x : {x.shape}")
#untuk dimensi 2, akan dibaca panjang array sebanyak 4 pada 4 dimensi array

print(f"Shape pada data y : {y.shape}")
#untuk dimensi 1, akan dibaca panjang array sebanyak 4 pada 1 dimensi array

print(f"Shape pada data z : {z.shape}")
#untuk dimensi 3
#(3,2,4) akan dibaca sebuah array memiliki 3 dimensi dan setiap dimensi memiliki 2 elemen, di dalam 2 elemen memiliki panjang sebanyak 4

Shape pada data x : (4, 4)
Shape pada data y : (4,)
Shape pada data z : (3, 2, 4)


In [31]:
#dimasukkan sebuah data matrix
a = np.array([[0,8,1,3],[8,8,4,8],[6,2,9,5]])
print(a)

[[0 8 1 3]
 [8 8 4 8]
 [6 2 9 5]]


In [32]:
#berfungsi untuk mencari baris index nomor n dan kolom index nomor n

#pada code ini akan dicari sebuah nilai di dalam baris index nomor 2 dan kolom index nomor 2
a[2,2]

9

In [33]:
#penggunaan nomor di depan berfungsi untuk memanggil baris sesuai pada matrix dimana mxn, dengan m adalah baris dan n adalah kolom
#berfungsi untuk memanggil semua nilai pada baris index nomor 2
print(f"Baris yang dipanggil : {a[2,:]}")

#penggunaan nomor di belakang berfungsi untuk memanggil kolom
#berfungsi untuk memanggil semua nilai pada kolom index nomor 3
print(f"Kolom yang dipanggil : {a[:,3]}")

Baris yang dipanggil : [6 2 9 5]
Kolom yang dipanggil : [3 8 5]


In [34]:
a[0,0:3:2]

#mencetak index baris nomor 0 index kolom nomor 0
#dari index 0 sampai index sebelum 3 dengan step 2 kali

array([0, 1])

In [35]:
a[2,1:3]

#akan mencetak index baris nomor 0 dan index kolom nomor 1
#mencetak index sebelum 3

array([2, 9])

In [38]:
#untuk mengganti nilai dalam baris dan kolom yang dipilih
a[0,0]=100
print(a)

[[100   8   1   3]
 [  8   8   4   8]
 [  6   2   9   5]]


In [39]:
#berfungsi untuk membuat matrix dengan ordo mxn. m adalah baris, n adalah kolom
np.ones((3,3))
#karena numeric yang dimasukkan adalah 1, maka matix yang keluar akan bernilai 1 di setiap index nya

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
#numeric yang digunakan adalah zero/0, sehingga matrix yang terbaca akan bernilai 1 di setiap indexnya
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [41]:
#untuk membuat matrix identitas
#hanya masukkan 1 bilangan, karena identitas sudah pasti berbentuk bujur sangkar
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [42]:
#untuk membuat matrix dengan dimensi 3

#pada code ini akan dibuat 2 dimensi, dimana setiap dimensi memiliki 3 elemen, dan disetiap elemen memiliki panjang sebanyak 4
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
#berfungsi untuk membuat matrix dengan ordo 3x2
#dimana semua nilai matrix akan terisi dengan bilangan 7
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [44]:
#akan mencetak angka random dengan ordo 4x3
np.random.rand(4,3)

array([[0.58758419, 0.90466579, 0.47997697],
       [0.49607004, 0.73752393, 0.26691275],
       [0.13271204, 0.96023479, 0.40357285],
       [0.34277025, 0.45366099, 0.54185956]])

In [45]:
#akan mencetak angka random pada matrix dengan range angka 1 sampai 8 (sesuai syntax pada pyhton -1) dengan ordo 4x4
np.random.randint(1,9,size=(4,4))

array([[5, 2, 4, 7],
       [6, 7, 1, 7],
       [2, 8, 6, 2],
       [5, 6, 5, 2]])

In [47]:
#membuat matrix 5x5

#mencetak matrix indentitas dengan ordo 5x5
k = np.identity(5)
print(k)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [48]:
#berfungsi untuk mengganti nilai identitas menjadi yang baru

#pada code ini nilai 1 akan diganti menjadi 4
j = 4*k
print(j)

[[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]


In [49]:
#matrix akan membentu ordo 5x5 dengan nilai semua bilangan matrix adalah 1
h = np.ones((5,5))

#selanjutnya memanggil matrix identitas dengan ordo yang sama agar tidak terjadi error
#nilai matrix identitas akan menjadi 5
g = np.identity(5)*5

#penggabungan h+g
#nilai matrix identitas akan menjadi 1+5, sementara bagian segitiga kanan dan kiri tetap 1
f = h+g
print(f)

[[6. 1. 1. 1. 1.]
 [1. 6. 1. 1. 1.]
 [1. 1. 6. 1. 1.]
 [1. 1. 1. 6. 1.]
 [1. 1. 1. 1. 6.]]


In [50]:
#mencetak penjumlahan matrix j dengan matrix f
gg = j+f
print(gg)

[[10.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1. 10.  1.]
 [ 1.  1.  1.  1. 10.]]


In [51]:
#dimasukkan data pada array aa sebagai berikut
aa = np.array([1,7,3,0,2])
print(aa)

[1 7 3 0 2]


In [52]:
#proses copy
bb = aa
print(bb)

[1 7 3 0 2]


In [53]:
#mengganti nilai pada index nomor 1 dengan nilai baru
bb[1] = 99
print(bb)

[ 1 99  3  0  2]


In [54]:
#karena bb = aa, maka ketika aa dicetak akan menghasilkan data terbaru dengan nilai bb yang sudah diubah
print(aa)

[ 1 99  3  0  2]


In [55]:
#akan dimasukkan data array sebagai berikut
cc = np.array([4,4,4,4,4])
print(cc)

[4 4 4 4 4]


In [56]:
#proses copy
dd = cc.copy()
print(cc)

[4 4 4 4 4]


In [57]:
#mengganti nilai pada index nomor 1 dengan nilai terbaru
dd[0]=104

#sehingga pencetakan akan menghasilkan data dd terbaru
print(dd)

[104   4   4   4   4]


In [58]:
#berbeda dengan code copy sebelumnya, pada penggunaan copy saat ini tidak akan merubah data lama menjadi data terbaru jika ingin mencetak cc
print(cc)

[4 4 4 4 4]


In [59]:
#dimasukkan data pada array sebagai berikut
cc = np.array([4,4,4,4,4])

#operasi pertambahan pada numpy, setiap index akan ditambahkan dengan 2
print(cc+5)

#operasi pengurangan pada numpy, setiap index akan dikurangi dengan 2
print(cc-5)

#operasi perkalian pada numpy, setiap index akan dikali dengan 5
print(cc*5)

#operasi pembagian pada numpy, setiap index akan dibagi dengan 5
print(cc/5)

#operasi perkalian pangkat pada numpy, setiap index akan dipangkatkan 5
print(cc**5)

[9 9 9 9 9]
[-1 -1 -1 -1 -1]
[20 20 20 20 20]
[0.8 0.8 0.8 0.8 0.8]
[1024 1024 1024 1024 1024]


In [60]:
#dimasukkan data array sebagai berikut
ee=np.array([2,1,2,1,2])
print(ee)

[2 1 2 1 2]


In [61]:
#operasi pertambahan pada numpy, setiap baris dan kolom dengan nomor index yang sama akan saling dioperasikan
print(cc+ee)

#operasi pengurangan pada numpy, setiap baris dan kolom dengan nomor index yang sama akan saling dioperasikan
print(cc-ee)

#operasi perkalian pada numpy, setiap baris dan kolom dengan nomor index yang sama akan saling dioperasikan
print(cc*ee)

#operasi pembagian pada numpy, setiap baris dan kolom dengan nomor index yang sama akan saling dioperasikan
print(cc/ee)

#operasi pangkat pada numpy, setiap baris dan kolom dengan nomor index yang sama akan saling dioperasikan
print(cc**ee)

[6 5 6 5 6]
[2 3 2 3 2]
[8 4 8 4 8]
[2. 4. 2. 4. 2.]
[16  4 16  4 16]


In [62]:
#penghitungan sin pada setiap nilai index
print(f"Hasil nilai sin pada matrix ee            : {np.sin(ee)}")

#penghitungan cos pada setiap nilai index
print(f"Hasil nilai cos pada matrix ee            : {np.cos(ee)}")

#penghitungan tan pada setiap nilai index
print(f"Hasil nilai tan pada matrix ee            : {np.tan(ee)}")

#penghitungan sin hiperbolik pada setiap nilai index
print(f"Hasil nilai sin hiperbolik pada matrix ee : {np.sinh(ee)}")

#penghitungan cos hiperbolik pada setiap nilai index
print(f"Hasil nilai cos hiperbolik pada matrix ee : {np.cosh(ee)}")

#penghitungan tangen hiperbolik pada setiap nilai index
print(f"Hasil nilai tan hiperbolik pada matrix ee : {np.tanh(ee)}")

#penghitungan akar kuadrat pada setiap nilai index
print(f"Hasil nilai akar kuadrat pada matrix ee   : {np.sqrt(ee)}")

Hasil nilai sin pada matrix ee            : [0.90929743 0.84147098 0.90929743 0.84147098 0.90929743]
Hasil nilai cos pada matrix ee            : [-0.41614684  0.54030231 -0.41614684  0.54030231 -0.41614684]
Hasil nilai tan pada matrix ee            : [-2.18503986  1.55740772 -2.18503986  1.55740772 -2.18503986]
Hasil nilai sin hiperbolik pada matrix ee : [3.62686041 1.17520119 3.62686041 1.17520119 3.62686041]
Hasil nilai cos hiperbolik pada matrix ee : [3.76219569 1.54308063 3.76219569 1.54308063 3.76219569]
Hasil nilai tan hiperbolik pada matrix ee : [0.96402758 0.76159416 0.96402758 0.76159416 0.96402758]
Hasil nilai akar kuadrat pada matrix ee   : [1.41421356 1.         1.41421356 1.         1.41421356]


In [63]:
#dimasukkan data pada array p sebagai berikut
p = np.array([[1,2,3,4],[4,1,3,2]])
print(p)

[[1 2 3 4]
 [4 1 3 2]]


In [64]:
#dimasukkan data pada array q sebagai berikut
q = np.array([[3,6,4,2],[5,6,4,10]])
print(q)

[[ 3  6  4  2]
 [ 5  6  4 10]]


In [65]:
#akan dihitung perkalian terhadapt matrix
#perkalian akan terhitung seperti perkalian biasa, setiap baris dan kolom yang sama akan beroperasi
r = p*q
print(r)

[[ 3 12 12  8]
 [20  6 12 20]]


In [66]:
#berbeda dengan menggunakan matmul
#matmul berfungsi untuk menghitung nilai perkalian matrix sesuai definisi pada perkalian matrix
s = np.matmul(p,q)
print(s)

#pada perkalian ini akan menghasilkan error, karena matrix 4x2 dikali dengan 4x2 tidak dapat dihitung

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [67]:
#dimasukkan data array t sebagai berikut
t = np.array([[5,4],[3,3],[9,2],[7,6]])
print(t)

#matrix dengan ordo 2x2

[[5 4]
 [3 3]
 [9 2]
 [7 6]]


In [68]:
#perkalian matrix sesuai definisi karena menggunakan matmul
u = np.matmul(p,t)
print(u)

#akan memiliki hasil karena matrix ordo 2x4 dapai dikali dengan matrix ordo 4x2

[[66 40]
 [64 37]]


In [69]:
v = p*t

#jika tidak menggunakan matmul akan error karena terdapat suatu nomor index matrix yang tidak memiliki pasangan pada index matrix kalinya

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [70]:
#diberikan data array pada p sebagai berikut
pp = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(pp)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
#berfungsi untuk mencari nilai minimal/nilai terkecil dalam matrix pp
qq = np.min(pp)
print(qq)

1


In [72]:
#axis pada sebuah array menjelaskan urutan pengindeksan dalam array
#akan mencetak index dalam baris pada matrix yang terdapat angka terkecilnya
rr = np.min(pp,axis=0)
print(rr)

[1 2 3 4]


In [73]:
#akan mencetak index dalam kolom pada matrix yang terdapat angka terkecilnya
ss = np.min(pp,axis=1)
print(ss)

[1 5 9]


In [74]:
#berfungsi untuk mencari nilai maksimum/nilai terbesar dalam matrix pp
tt = np.max(pp)
print(tt)

12


In [75]:
#akan mencetak index dalam baris pada matrix yang terdapat angka terbesarnya
uu = np.max(pp,axis=0)
print(uu)

[ 9 10 11 12]


In [76]:
#akan mencetak index dalam kolom pada matrix yang terdapat angka terbesarnya
vv = np.max(pp,axis=1)
print(vv)

[ 4  8 12]


In [77]:
ww = np.sum(pp)
print(ww)

#sum berfungsi untuk menjumlahkan semua nilai yang terdapat pada data array pp

78


In [78]:
xx = np.sum(pp,axis=0)
print(xx)

#untuk mencetak jumlah pada kolom-kolom matrix
#misal pada index kolom nomor 0 adalah 1 5 9 hasilnya adalah 15
#kemudian pada index kolom nomor 1 adalah 2 6 10 hasilnya adalah 18, dst

[15 18 21 24]


In [79]:
yy = np.sum(pp,axis=1)
print(yy)

#untuk mencetak jumlah pada baris-baris matrix
#misal pada index baris nomor 0 adalah 1 2 3 4 hasilnya adalah 10
#kemudian pada index baris nomor 1 adalah 5 6 7 8 hasilnya adalah 26, dst

[10 26 42]
